version: "3"

services:

  # ================================= Grafana  ================================= 
  grafana:
    image: grafana/grafana:master
    container_name: muta-granafa
    restart: on-failure
    ports:
      - "8600:3000"
    volumes:
      - "./config/grafana/grafana.ini:/etc/grafana/grafana.ini"
      - "./config/grafana/dashboards:/var/lib/grafana/dashboards"
      - "./config/grafana/provisioning:/etc/grafana/provisioning"
      - "./data/grafana/log:/var/log/grafana"
    environment:
      GF_EXPLORE_ENABLED: "true"
      GF_RENDERING_SERVER_URL: http://renderer:8081/render
      GF_RENDERING_CALLBACK_URL: http://grafana:3000/
      GF_LOG_FILTERS: rendering:debug
    networks:
      - mercury-monitor  

  # link https://github.com/grafana/grafana-image-renderer/blob/master/docs/remote_rendering_using_docker.md    
  renderer:
    image:  grafana/grafana-image-renderer:2.0.0
    container_name: muta-grafana-image-renderer
    ports:
      - 8081
    networks:
      - mercury-monitor 
    
  # ================================= Prometheus ================================= 
  prometheus:
    image: prom/prometheus:v2.20.1
    container_name: muta-prometheus
    hostname: prometheus
    restart: on-failure
    volumes:
      - ./config/promethues/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./data/prometheus:/prometheus
    ports:
      - "9090:9090"
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.console.libraries=/usr/share/prometheus/console_libraries
      - --web.console.templates=/usr/share/prometheus/consoles
      - --web.enable-lifecycle
    networks:
      - mercury-monitor   
      
  # ================================= Loki  ================================= 
  loki:
    image: grafana/loki:1.5.0
    container_name: muta-loki
    restart: on-failure
    ports:
      - "8601:3100"
    volumes:
      - ./config/loki:/etc/loki
      - ./data/nginx:/var/log/nginx
      - ./data/loki:/tmp/loki
    command: -config.file=/etc/loki/loki-local-config.yaml
    networks:
      - mercury-monitor    

networks:
  mercury-monitor:
    driver: bridge 