version: '3'

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    privileged: true
    ports:
      - 8432:5432
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: mercury
      PGDATA: /var/lib/postgresql/data/pgdata
      entrypoint: /entrypoint.sh
    volumes:
      #      - ./pg_data/data:/var/lib/postgresql/data/pgdata
      - ./config/create_table.sql:/docker-entrypoint-initdb.d/create_table.sql
      - ./config/my-postgres.conf:/etc/postgresql/postgresql.conf
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
