---

- name: check monitor dir
  stat:
    path: "{{ monitor_agent_dir }}"
  register: file_status
- name: create monitor dir
  file:
    path: "{{ monitor_agent_dir }}"
    state: directory
  when:
    file_status.stat.exists == False

- name: copy docker-compose.yml
  copy:
    src: ../agent/docker-compose.yml
    dest: "{{ monitor_agent_dir }}/docker-compose.yml"
    mode: 0755
- name: copy config
  copy:
    src: ../agent/config
    dest: "{{ monitor_agent_dir }}"
    mode: 0755
- name: copy env
  copy:
    src: ../agent/.env.example
    dest: "{{ monitor_agent_dir }}/.env"
    mode: 0755

- name: sed env
  shell: sed -i '' 's/LOG_COLLECT_PATH/{{ log_path }}/' "{{ monitor_agent_dir }}/.env"
- name: sed promtail
  shell: sed -i '' 's/LOKI_ADDRESS/{{ loki_address }}/' "{{ monitor_agent_dir }}/config/promtail/promtail-config.yaml"

# - name: sed env
#   shell: sed -i '' 's/LOG_COLLECT_PATH/{{ log_path }}/' roles/agent/templates/.env.j2 && sed -i '' 's/jaeger-collector:14250/192.168.1.2:14250/' roles/agent/templates/.env.j2

# - name: sed promtail
#   shell: sed -i '' 's/LOKI_ADDRESS/{{ loki_address }}/' roles/agent/templates/promtail-config.yaml.j2

# - name: mkdir monitor agent dir
#   file: path={{ monitor_dir }}  state=directory mode=0755 recurse=yes

# - name: mkdir monitor agent config dir
#   file: path={{ monitor_dir }}/config/promtail  state=directory mode=0755 recurse=yes 

# - name: copy docker-compose.yml
#   template: src=docker-compose.yml.j2 dest={{ monitor_dir }}/docker-compose.yml

# - name: copy .env
#   template: src=.env.j2 dest={{ monitor_dir }}/.env 

# - name: copy promtail-config.yaml
#   template: src=promtail-config.yaml.j2 dest={{ monitor_dir }}/config/promtail/promtail-config.yaml

# - name: start node-exporter jaeger-agent
#   shell: cd {{ monitor_dir }} &&  docker-compose up -d