deploy_path: "/home/ckb/mercury-test"
mercury_repo: "https://github.com/nervosnetwork/mercury.git"
mercury_version: "dev"
net_type: "testnet"
kill_name: "devtools/config/testnet_config.toml"
db_password: "123456"
